import { writeFile, mkdir } from "node:fs/promises";
import { azava } from "../lib/azava.js";

async function main() {
  console.log("Fetching schema from Azava...");
  const schema = await azava.schema();

  await mkdir("data", { recursive: true });
  await writeFile("data/schema.json", JSON.stringify(schema, null, 2));
  console.log("Written to data/schema.json");

  // Also write a human-readable summary for Claude Code to reference
  const nodeTypes = schema.nodeTypes || schema.node_types || [];
  const edgeTypes = schema.edgeTypes || schema.edge_types || [];

  const lines = [
    "# Knowledge Graph Schema",
    "",
    `> Auto-generated by \`npm run fetch-schema\`. Do not edit manually.`,
    "",
    "## Node Types",
    "",
    ...nodeTypes.map((t: Record<string, string>) =>
      `- **${t.name || t.label}** (${t.category || "unknown"})${t.description ? ` — ${t.description}` : ""}`
    ),
    "",
    "## Edge Types",
    "",
    ...edgeTypes.map((t: Record<string, string>) =>
      `- **${t.name || t.label}**: ${t.source_node_type || t.from} → ${t.target_node_type || t.to}${t.description ? ` — ${t.description}` : ""}`
    ),
    "",
  ];

  await writeFile("data/schema.md", lines.join("\n"));
  console.log("Written to data/schema.md");
}

main();
